---
- name: Update and Upgrade Packages
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
      become: yes

- name: Install Docker, Python 3, Node.js, and Docker containers
  hosts: localhost
  gather_facts: true

  vars:
    local_folder_path: "/home/liam/Desktop/Projekt"

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - python3
        - python3-pip
        - nodejs
        - npm
      become: yes

    - name: Upgrade all packages (optional, depending on your requirements)
      apt:
        upgrade: yes
        autoremove: yes
      become: yes

    - name: Install Docker Python module
      apt:
        name: python3-docker
        state: present
      become: yes

    - name: Pull Docker images
      command: "docker pull {{ item }}"
      loop:
        - ghcr.io/9maiil/ansibleplaybook/dockermongodb:1
        - ghcr.io/9maiil/ansibleplaybook/dockerapache:1
      become: yes

    - name: Start MongoDB Docker container
      docker_container:
        name: mongodb_container
        image: ghcr.io/9maiil/ansibleplaybook/dockermongodb:1
        state: started
        ports:
          - "27017:27017"
        volumes:
          - "/home/liam/Desktop/Projekt/AnsiblePlaybook/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js"
      become: yes

    - name: Start Apache Docker container
      docker_container:
        name: apache_container
        image: ghcr.io/9maiil/ansibleplaybook/dockerapache:1
        state: started
        ports:
          - "80:80"
      become: yes

    - name: Run npm commands
      command: "npm {{ item }}"
      loop:
        - "init -y"
        - "install express mongoose cors"
      args:
        chdir: "{{ local_folder_path }}"
      become: yes
